# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'artistsBlock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock
  pod "SDWebImage", "~>4.3.3"
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
#   pod 'React', :path => '../node_modules/react-native'
# pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  target 'artistsBlock-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    # pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  end

  target 'artistsBlockTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'artistsBlock-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock-tvOS

end
