# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'artistsBlock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock
  pod "SDWebImage", "~>4.3.3"
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '~> 5.20.1'
  pod 'Firebase/Storage', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'artistsBlock-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    # pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

    # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end

  target 'artistsBlockTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'artistsBlock-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock-tvOS

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "react-native"
      target.remove_from_project
    end
  end
end