# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'artistsBlock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock
  pod "SDWebImage", "~>4.3.3"

  target 'artistsBlock-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'artistsBlockTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'artistsBlock-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for artistsBlock-tvOS

end
